name: Run CI tests

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4

      - name: ğŸ”§ Set up Taskfile
        uses: go-task/setup-task@v1

      - name: ğŸ”§ Setup uv
        uses: astral-sh/setup-uv@v6

      - name: ğŸ Install Python
        run: uv python install

      - name: ğŸš€ Run CI task
        run: task ci